name: Run Cypress Tests

on:
  push:
    branches:
      - main  # ou qualquer branch que você deseja monitorar
  pull_request:
    branches:
      - main  # ou qualquer branch para PR

jobs:
  cypress-run:
    runs-on: ubuntu-latest  # Define o ambiente de execução (Ubuntu, no caso)
    
    steps:
      # Passo 1: Baixar o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Passo 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Defina a versão do Node.js que você está usando

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          npm install cypress
          npm install -D cypress-xpath
          npm install -D cypress-iframe


      # Passo 4: Executar os testes do Cypress
      - name: Run Cypress Tests
        run: |
          npx cypress run  # Executa os testes no ambiente CI

      # Passo 5: Fazer upload dos resultados (opcional)
      - name: Upload Cypress Videos and Screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/videos/*
            cypress/screenshots/*